# Generated by Django 3.2.6 on 2021-08-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['id'], 'verbose_name': 'Línea de pedido', 'verbose_name_plural': 'Líneas de pedidos'},
        ),
        migrations.AlterModelTable(
            name='orderline',
            table='orderlines',
        ),
    ]
